options {
    directory "/var/cache/bind";
    recursion no;
    allow-query { any; };
    listen-on { 172.20.0.4; };
};

zone "example.lab." {
    type master;
    file "/etc/bind/zones/example.lab.zone";
};
